# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:                  Ethical Frenchie
description:            We are a family and friends based French Bulldog Breeder located in New York, NY. We welcome you to Learn more about us and our kennelshare program.
url:                    "" # Site base hostname & protocol, e.g. http://example.com
baseurl:                # Site subpath, e.g. /blog
lang:                   en
logo:                   logo-dark.png
logo_light:             logo-light.png
permalink:              /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:            "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:                /uploads/ # Path to post content assets directory i.e post images, pdfs etc
template:               base

paginate:               6 # Number of posts displayed on blog page
paginate_path:          "/blog/:num/" # Blog path

# Default author settings
author:
  name:                 James Harrison
  avatar:               avatar-tom.png
  title:                Support     
  bio:                  I am the CEO of this company, loved by everyone, just plain awesome so you want to follow me all the time.
  url:
  email:                james@ashlandharrison.com
  website:
  facebook:             https://www.facebook.com/ethicalfrenchie
  flickr:
  dribbble:
  github:
  googleplus:
  instagram:            https://www.instagram.com/ethicalfrenchie
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  john:
    name:               James Harrison
    title:              Owner     
    avatar:             james.jpg
  evan:
    name:               Renee Harrison
    title:              Support    
    avatar:             renee.jpg
  sara:
    name:               Thomas Holloman
    title:              Houses "May" and "April"    
    avatar:             avatar-sara.png
  alex:
    title:              Records & Compliance   
    name:               Ely Tenorio
    avatar:             avatar-alex.png
  tom:
    title:              Developer     
    name:               Tom Farrell
    avatar:             avatar-tom.png

navbar:
  layout:               default # default, center
  color:                dark # text color, dark or light
  animation:            true
  sticky:               true
  search:               false

footer:                 # Default footer image settings
  style:                secondary # default, muted, primary, secondary
  layout:               columns # center or columns
  copyright:            Made by a <a href="https://ivanchromjak.com/">human</a> somewhere on the planet earth.

mailchimp:
  form_action:          000000
  hidden_name:          000000
  
google_analytics:       # Google analytics code, get your code here https://www.google.com/analytics/
google_maps_api_key:    # Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key

disqus:
  shortname:            # Disqus comments shortname, requires Disqus account https://disqus.com/

instagram_accesstoken:  38756782.1677ed0.57e2c5113463487f801e66e975066677

donations:
  paypal:
    id:                 # PayPal button ID
    navbar:             # true

# Social share buttons
social_share:
  twitter:              true
  facebook:             true
  linkedin:             true
  pinterest:            true
  reddit:               true

# Social buttons
social_networks:
  email:                adopt@ethicalfrenchie.com
  website:
  facebook:             https://www.facebook.com/ethicalfrenchie
  flickr:
  dribbble:
  github:
  googleplus:
  instagram:            https://www.instagram.com/ethicalfrenchie
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:

# Build settings
markdown:               kramdown
highlighter:            rouge
kramdown:
  toc_levels:           "2"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

exclude: 
  - vendor
  - .bundle
  - .sass-cache
  - config
  - Gemfile
  - Gemfile.lock
  - node_modules
  - log
  - tmp
  - Rakefile
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:                compressed

# collections:
collections:
  blocks:
    output:             false
  sidebars:
    output:             false
  faqs:
    output:             false
  puppies:
    output:             true

# Defaults
defaults:
  # _posts
  - scope:
      path:                 ""
      type:                 posts
    values:
      layout:               post
      section:              large
      sidebar: 
        right:              blog
      comments:             # true
      share:                true
      related:              true
      mailchimp:            true
      navbar:
        transparent:        true
        transparent_color:  light
      header:
        layout:             center
        background_overlay: "rgba(0, 0, 0, 0.5)"
        color:              light
        header_size:        large
        heading_size:       medium
        parallax:           true
  # _pages
  - scope:
      path:                 ""
      type:                 pages
    values:
      layout:               page
  # _puppies
  - scope:
      path:                 ""
      type:                 puppies
    values:
      layout:               page