source "https://rubygems.org"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-gist"
gem "jekyll-sitemap"
gem "jemoji"
gem 'jekyll-webp', '~> 1.0'
gem "jekyll-gzip"
gem "jekyll-redirect-from"