backend:
  name: github
  repo: jamesETF/EthicalFrenchie_Final
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads


